Repository pyrddlgym-project/pyRDDLGym, pull requests merged in 2022-12, with the labels that each got.

#130 Merge lifted sim to rddl env
  pyRDDLGym/Core/Compiler/RDDLDecompiler.py
  pyRDDLGym/Core/Compiler/RDDLLevelAnalysis.py
  pyRDDLGym/Core/Compiler/RDDLLiftedModel.py
  pyRDDLGym/Core/Compiler/RDDLModel.py
  pyRDDLGym/Core/Compiler/__init__.py
  pyRDDLGym/Core/Env/RDDLEnv.py
  pyRDDLGym/Core/Grounder/RDDLGrounder.py
  pyRDDLGym/Core/Simulator/LiftedRDDLSimulator.py
  pyRDDLGym/Core/Simulator/LiftedRDDLTypeAnalysis.py
  pyRDDLGym/Core/Simulator/RDDLDependencyAnalysis.py
  pyRDDLGym/Core/Simulator/RDDLSimulator.py
  pyRDDLGym/Core/Simulator/RDDLTensors.py
  pyRDDLGym/Examples/Racecar/domain.rddl
  pyRDDLGym/GymExample.py
  pyRDDLGym/GymExample2.py
  pyRDDLGym/Visualizer/CartPoleViz.py
  pyRDDLGym/Visualizer/ElevatorViz.py
  pyRDDLGym/Visualizer/HVACDisplay.py
  pyRDDLGym/Visualizer/MarsRoverViz.py
  pyRDDLGym/Visualizer/MountainCarViz.py
  pyRDDLGym/Visualizer/MovieGenerator.py
  pyRDDLGym/Visualizer/PowerGenViz.py
  pyRDDLGym/Visualizer/RacecarViz.py
  pyRDDLGym/Visualizer/RecSimViz.py
  pyRDDLGym/Visualizer/ReservoirViz.py
  pyRDDLGym/Visualizer/TextViz.py
  pyRDDLGym/Visualizer/UAVsViz.py
  pyRDDLGym/Visualizer/WildfireViz.py
  pyRDDLGym/old/GymExample2.py
  pyRDDLGym/old/RDDLDependencyAnalysis.py
  pyRDDLGym/old/RDDLSimulator.py
  pyRDDLGym/old/__init__.py
Labels: Urgent

#131 Xadd
  pyRDDLGym/Core/Compiler/RDDLModel.py
  pyRDDLGym/Core/Grounder/RDDLGrounder.py
  pyRDDLGym/Core/Simulator/RDDLSimulator.py
  pyRDDLGym/Policies/Agents.py
  pyRDDLGym/Visualizer/visualize_dbn.py
  pyRDDLGym/XADD/RDDLLevelAnalysisXADD.py
  pyRDDLGym/XADD/RDDLModelXADD.py
  pyRDDLGym/XADD/RDDLSimulatorXADD.py
  pyRDDLGym/XADD/__init__.py
  pyRDDLGym/tests/test_dbn_vis.py
  pyRDDLGym/tests/test_xadd.py
Labels: enhancement, Urgent

#128 Ast to jax compiler
  pyRDDLGym/Core/Jax/JaxRDDLBackpropPlanner.py
  pyRDDLGym/Core/Jax/JaxRDDLCompiler.py
  pyRDDLGym/Core/Jax/JaxRDDLCompilerWithGrad.py
  pyRDDLGym/Core/Jax/JaxRDDLSimulator.py
  pyRDDLGym/Core/Jax/__init__.py
  pyRDDLGym/Examples/Reservoir/domain.rddl
  pyRDDLGym/Examples/Reservoir/instance0.rddl
  pyRDDLGym/JaxExample.py
  requirements_jax.txt
Labels: enhancement, Urgent

#133 Interop of rddl models
  pyRDDLGym/Core/Compiler/RDDLLevelAnalysis.py
  pyRDDLGym/Core/Compiler/RDDLLiftedModel.py
  pyRDDLGym/Core/Compiler/RDDLModel.py
  pyRDDLGym/Core/Env/RDDLEnv.py
  pyRDDLGym/Core/Grounder/RDDLGrounder.py
  pyRDDLGym/Core/Jax/JaxRDDLBackpropPlanner.py
  pyRDDLGym/Core/Jax/JaxRDDLCompiler.py
  pyRDDLGym/Core/Jax/JaxRDDLSimulator.py
  pyRDDLGym/Core/Simulator/RDDLSimulator.py
  pyRDDLGym/Core/Simulator/RDDLTensors.py
  pyRDDLGym/JaxExample.py
Labels: Urgent

#135 Merge new api changes to xadd
  pyRDDLGym/Visualizer/visualize_dbn.py
  pyRDDLGym/XADD/RDDLLevelAnalysisXADD.py
  pyRDDLGym/XADD/RDDLModelXADD.py
  pyRDDLGym/XADD/RDDLSimulatorXADD.py
Labels: bug, Urgent

#129 Add RDDLSimAgent
  pyRDDLGym/Policies/RDDLSimAgent.py
  pyRDDLGym/RDDLSimClientExample.py
Labels: enhancement
